title: Testing setup. 
author: Edward J. Bickels
email: ejbickels@mail.mccneb.edu
description: > # this means to ignore newlines until "twitter_username:"
  Currently testing this. Will make this into a launchpad for openpilot or something. Idk. dont hold me to anything. 
# social links
github_username: roxasthenobody98

theme: minima
